# fly.toml app configuration file generated for withered-glade-8768 on 2023-06-05T20:29:57-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "withered-glade-8768"
primary_region = "scl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
[env]
  SKIP_PREFLIGHT_CHECK=true
