# fly.toml app configuration file generated for rickandmorty on 2023-06-06T19:55:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rickandmorty"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
